- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Install Gnome desktop
  apt:
    name: 
      - task-gnome-desktop
    state: present
  register: gnomeStatus

- name: Install Gnome desktop
  apt:
    name: 
      - gnome-shell-extension-dashtodock
    state: present
  when: ansible_distribution == 'Debian'

- name: Start gnome display manager service
  ansible.builtin.service:
    name: gdm
    state: started
    enabled: yes

- name: Start dbus service
  ansible.builtin.service:
    name: dbus
    state: started
    enabled: yes

- name: Gnome - Download bottompanel extension
  become_user: "{{ ansible_user }}"
  ansible.builtin.shell: rm -rf ~/.local/share/gnome-shell/extensions/; git clone https://github.com/Thoma5/gnome-shell-extension-bottompanel.git; mv gnome-shell-extension-bottompanel ~/.local/share/gnome-shell/extensions/
  ignore_errors: true

- name: Enable gnome shell extensions
  become_user: "{{ ansible_user }}"
  dconf:
    key: "/org/gnome/shell/enabled-extensions"
    value: "['dash-to-dock@micxgx.gmail.com', 'desktop-icons@csoriano', 'places-menu@gnome-shell-extensions.gcampax.github.com', 'user-theme@gnome-shell-extensions.gcampax.github.com', 'workspace-indicator@gnome-shell-extensions.gcampax.github.com', 'dash-to-panel@jderose9.github.com', 'apps-menu@gnome-shell-extensions.gcampax.github.com', 'auto-move-windows@gnome-shell-extensions.gcampax.github.com', 'bottompanel@tmoer93']"

- name: Gnome - Copy wallpaper file
  copy: src=../files/secubian_wallpaper.png dest=/home/{{ ansible_user }}/.wallpaper_secubian.png owner="{{ ansible_user }}" group="{{ ansible_user }}" mode=600

- name: Gnome - Set Desktop Wallpaper
  become_user: "{{ ansible_user }}"
  dconf: key="/org/gnome/desktop/background/picture-uri" value="'file:///home/{{ ansible_user }}/.wallpaper_secubian.png'"

- name: Gnome - Set Lockscreen Wallpaper
  become_user: "{{ ansible_user }}"
  dconf: key="/org/gnome/desktop/lockscreen/picture-uri" value="'file:///home/{{ ansible_user }}/.wallpaper_secubian.png'"

- name: Gnome - Enable maximize,minimize button on window
  become_user: "{{ ansible_user }}"
  dconf: key="/org/gnome/desktop/wm/preferences/button-layout" value="'appmenu:minimize,maximize,close'"

- name: Gnome - Set list view in window
  become_user: "{{ ansible_user }}"
  dconf: key="/org/gnome/nautilus/preferences/default-folder-viewer" value="'list-view'"

- name: Gnome - Set default Gnome font 
  become_user: "{{ ansible_user }}"
  dconf: key="/org/gnome/desktop/interface/font-name" value="'Cantarell 10'"

- name: Gnome - Set font size
  become_user: "{{ ansible_user }}"
  dconf: key="/org/gnome/desktop/interface/monospace-font-name" value="'Monospace 10'"

- name: Gnome - disable sleep when on AC power
  become_user: "{{ ansible_user }}"
  dconf: key="/org/gnome/settings-daemon/plugins/power/sleep-inactive-ac-type" value="'nothing'"

- name: Gnome - disable sleep when on Battery power
  become_user: "{{ ansible_user }}"
  dconf: key="/org/gnome/settings-daemon/plugins/power/sleep-inactive-battery-type" value="'nothing'"

- name: Gnome - disable screen sleep off
  become_user: "{{ ansible_user }}"
  dconf: key="/org/gnome/settings-daemon/plugins/power/idle-dim" value="false"

- name: Gnome - disable session idle
  become_user: "{{ ansible_user }}"
  dconf: key="/org/gnome/desktop/session/idle-delay" value="uint32 0"

- name: Gnome - disable auto screen lock
  become_user: "{{ ansible_user }}"
  dconf: key="/org/gnome/desktop/screensaver/lock-enabled" value="false"

- name: Gnome - Disabling Animations
  become_user: "{{ ansible_user }}"
  dconf: key="/org/gnome/desktop/interface/enable-animations" value="false"

- name: Enable Gnome Shell extension - apps-menu@gnome-shell-extensions.gcampax.github.com
  become_user: "{{ ansible_user }}"
  command: gnome-shell-extension-tool --enable-extension apps-menu@gnome-shell-extensions.gcampax.github.com

- name: Enable Gnome Shell extension - auto-move-windows@gnome-shell-extensions.gcampax.github.com
  become_user: "{{ ansible_user }}"
  command: gnome-shell-extension-tool --enable-extension auto-move-windows@gnome-shell-extensions.gcampax.github.com

- name: Enable Gnome Shell extension - caffeine@patapon.info
  become_user: "{{ ansible_user }}"
  command: gnome-shell-extension-tool --enable-extension caffeine@patapon.info

- name: Enable Gnome Shell extension - desktop-icons@csoriano
  become_user: "{{ ansible_user }}"
  command: gnome-shell-extension-tool --enable-extension desktop-icons@csoriano

- name: Enable Gnome Shell extension - places-menu@gnome-shell-extensions.gcampax.github.com
  become_user: "{{ ansible_user }}"
  command: gnome-shell-extension-tool --enable-extension places-menu@gnome-shell-extensions.gcampax.github.com

- name: Enable Gnome Shell extension - user-theme@gnome-shell-extensions.gcampax.github.com
  become_user: "{{ ansible_user }}"
  command: gnome-shell-extension-tool --enable-extension user-theme@gnome-shell-extensions.gcampax.github.com

- name: Enable Gnome Shell extension - workspace-indicator@gnome-shell-extensions.gcampax.github.com
  become_user: "{{ ansible_user }}"
  command: gnome-shell-extension-tool --enable-extension workspace-indicator@gnome-shell-extensions.gcampax.github.com

#- name: Enable Gnome Shell extension - dash-to-panel@jderose9.github.com
#  become_user: "{{ ansible_user }}"
#  command: gnome-shell-extension-tool --enable-extension dash-to-panel@jderose9.github.com

#- name: Gnome - Configure dash-to-panel
#  become_user: "{{ ansible_user }}"
#  dconf: key="/org/gnome/shell/extensions/dash-to-panel/panel-size" value="38"

#- name: Gnome - Configure dash-to-panel - leftbox font size
#  become_user: "{{ ansible_user }}"
#  dconf: key="/org/gnome/shell/extensions/dash-to-panel/leftbox-size" value="13"

#- name: Gnome - Configure dash-to-panel
#  become_user: "{{ ansible_user }}"
#  dconf: key="/org/gnome/shell/extensions/dash-to-panel/dot-style-focused" value="'DOTS'"

#- name: Gnome - Configure dash-to-panel
#  become_user: "{{ ansible_user }}"
#  dconf: key="/org/gnome/shell/extensions/dash-to-panel/dot-style-unfocused" value="'DOTS'"

- name: Gnome - Set/Remove favorites apps from Dash-panel
  become_user: "{{ ansible_user }}"
  dconf: key="/org/gnome/shell/favorite-apps" value="['firefox-esr.desktop','org.gnome.Evolution.desktop','terminator.desktop','code.desktop','gedit.desktop','org.keepassxc.KeePassXC.desktop','zulucrypt-gui.desktop','org.remmina.Remmina.desktop','sqlitebrowser.desktop']"

- name: Gnome Application Theme vimix-gtk-themes - Clone a github repository
  become_user: "{{ ansible_user }}"
  git:
    repo: https://github.com/vinceliuice/vimix-gtk-themes.git
    dest: /tmp/vimix-gtk-themes
    clone: yes
    update: yes

- name: Gnome Application Theme vimix-gtk-themes - Installation
  become_user: "{{ ansible_user }}"
  ansible.builtin.shell: chmod +x /tmp/vimix-gtk-themes/install.sh; /tmp/vimix-gtk-themes/install.sh -c dark -t doder -s compact; rm -rf /tmp/vimix-gtk-themes;

- name: Gnome Application Theme - Apply vimix-gtk-themes
  become_user: "{{ ansible_user }}"
  dconf: key="/org/gnome/desktop/interface/gtk-theme" value="'vimix-dark-compact-doder'"

- name: Gnome Application Theme - Apply vimix-gtk-themes
  become_user: "{{ ansible_user }}"
  dconf: key="/org/gnome/shell/extensions/user-theme/name" value="'vimix-dark-compact-doder'"

- name: Gnome Icon Theme flat-remix-icons - Transfert
  become: true
  copy: 
    src: ../files/theme-icons/Flat-Remix-Blue-Dark.tar.gz
    dest: /usr/share/icons/

- name: Gnome Icon Theme flat-remix-icons - Installation
  ansible.builtin.shell: tar xvzf Flat-Remix-Blue-Dark.tar.gz
  args:
    chdir: /usr/share/icons/

- name: Gnome Icon Theme - flat-remix-icons
  become_user: "{{ ansible_user }}"
  dconf: key="/org/gnome/desktop/interface/icon-theme" value="'Flat-Remix-Blue-Dark'"

- name: Gnome - Disable automount
  become_user: "{{ ansible_user }}"
  dconf: key="/org/gnome/desktop/media-handling/automount" value="false"

- name: Gnome - Disable automount-open
  become_user: "{{ ansible_user }}"
  dconf: key="/org/gnome/desktop/media-handling/automount-open" value="false"

- name: Gnome - Enable mouse tap-to-click
  become_user: "{{ ansible_user }}"
  dconf: key="/org/gnome/desktop/peripherals/touchpad/tap-to-click" value="true"

- name: Gnome - Change default view in nautilus
  become_user: "{{ ansible_user }}"
  dconf: key="/org/gnome/nautilus/preferences/default-folder-viewer" value="'list-view'"

- name: Gnome - Sort Directories first
  become_user: "{{ ansible_user }}"
  dconf: key="/org/gnome/nautilus/preferences/sort-directories-first" value="true"

- name: Gnome - Set default view columns in nautilus
  become_user: "{{ ansible_user }}"
  dconf: key="/org/gnome/nautilus/list-view/default-visible-columns" value="['name', 'size', 'type', 'date_modified', 'permissions', 'owner', 'group']"

- name: Gnome - Change sort in nautilus
  become_user: "{{ ansible_user }}"
  dconf: key="/org/gnome/nautilus/preferences/default-sort-order" value="'type'"

- name: GEdit - Change highlight current line theme
  lineinfile:
    dest: "/usr/share/gtksourceview-4/styles/tango.xml"
    create: yes
    mode: 0644
    line: '  <!--<style name="current-line"                background="aluminium1"/>-->'
    regexp: '^  <style name="current-line"                background="aluminium1"/>'

- name: GEdit - Change highlight current line number theme
  lineinfile:
    dest: "/usr/share/gtksourceview-4/styles/tango.xml"
    create: yes
    mode: 0644
    line: '  <!--<style name="current-line-number"         background="aluminium1"/>-->'
    regexp: '^  <style name="current-line-number"         background="aluminium1"/>'
    
- name: Gnome - Set dock-position
  become_user: "{{ ansible_user }}"
  dconf: key="/org/gnome/shell/extensions/dash-to-dock/{{ item.key }}" value="{{ item.value }}"
  with_items:
    - { key: "animate-show-apps", value: "false" }
    - { key: "dash-max-icon-size", value: "25" }
    - { key: "dock-position", value: "'LEFT'" }
    - { key: "isolate-monitors", value: "true" }
    - { key: "isolate-workspaces", value: "true" }
    - { key: "multi-monitor", value: "true" }
    - { key: "running-indicator-style", value: "'DASHES'" }
    - { key: "show-apps-at-top", value: "true" }
    - { key: "show-windows-preview", value: "false" }

- name: Gnome - Set Privacy
  become_user: "{{ ansible_user }}"
  dconf: key="/org/gnome/desktop/privacy/{{ item.key }}" value="{{ item.value }}"
  with_items:
    - { key: "disable-camera", value: "true" }
    - { key: "disable-microphone", value: "true" }
    - { key: "hide-identity", value: "true" }
    - { key: "privacy-screen", value: "true" }
    - { key: "remember-recent-files", value: "false" }
    - { key: "report-technical-problems", value: "false" }
    - { key: "remember-app-usage", value: "false" }
    - { key: "send-software-usage-stats", value: "false" }

- name: Gnome - Set Security
  become_user: "{{ ansible_user }}"
  dconf: key="/org/gnome/desktop/media-handling/{{ item.key }}" value="{{ item.value }}"
  with_items:
    - { key: "automount", value: "false" }
    - { key: "automount-open", value: "false" }

- name: Gnome - Add directories bookmarks
  become_user: "{{ ansible_user }}"
  lineinfile:
    dest: "~/.config/gtk-3.0/bookmarks"
    create: yes
    mode: 0644
    line: "file:////{{ item.path }}"
    regexp: "^file:////{{ item.path }}"
  with_items:
    - { path: "{{ casesDir }}" }
    - { path: "{{ documentationDir }}" }
    - { path: "{{ playbooksDir }}" }
    - { path: "{{ toolsDir }} "}

