- name: "Homer | Copy preferences"
  become_user: "{{ ansible_user }}"
  ansible.builtin.copy: 
    src  : ../files/homer/
    dest : "/home/{{ ansible_user }}/.homer/"

- name: "Homer | Run docker container"
  community.docker.docker_container:
    name: homer
    image: b4bz/homer:latest
    state: started
    restart: true
    restart_policy: "always"
    volumes:
     - "/home/{{ ansible_user }}/.homer/:/www/assets"
    ports:
     - "8080:8080"

