- name: "Keepass | Generate password"
  become_user: "{{ ansible_user }}"
  shell: "keepassxc-cli generate -L 64 -lUn"
  delegate_to: localhost
  register: result
  ignore_errors: False

- name: "set password"
  become_user: "{{ ansible_user }}"
  ansible.builtin.set_fact: "password={{ result.stdout }}"

