- name: "Jupyter Notebook | set PythonVersion"
  ansible.builtin.set_fact:
    python_version : "3.9.18" 

- name: "Jupyter Notebook | Install jupyter Python3 modules"
  become_user: "{{ ansible_user }}"
  ansible.builtin.pip:
    name: 
      - scipy
      - numpy
      - matplotlib
      - azure-mgmt-resource
      - msticpy
      - msticpy[azure]
      - pandas
      - poetry
    virtualenv: "$HOME/.pyenv/versions/{{ python_version }}"
    virtualenv_command: $HOME/.pyenv/bin/pyenv virtualenv {{ python_version }}
  tags: jupyter

- name: "Jupyter Notebook | Download secubian-JupyterNotebook"
  become_user: "{{ ansible_user }}"
  git:
    repo: "{{ item.repo }}"
    accept_hostkey: yes
    dest: "{{ item.dest }}"
    recursive: yes
    force: yes
  with_items:
    - { repo: "https://github.com/kidrek/secubian-JupyterNotebook.git", dest: "{{ playbooksDir }}/JupyterNotebook" }
  tags: jupyter

- name: "Jupyter Notebook | Requirements tools installation"
  become_user: "{{ ansible_user }}"
  ansible.builtin.pip:
    requirements: "{{ playbooksDir }}/JupyterNotebook/requirements.txt"
    virtualenv: "$HOME/.pyenv/versions/{{ python_version }}"
    virtualenv_command: "$HOME/.pyenv/bin/pyenv virtualenv {{ python_version }}"

- name: "Jupyter Notebook | Add alias"
  become_user: "{{ ansible_user }}"
  lineinfile:
    dest: "~/.aliases"
    create: yes
    mode: 0644
    line: "alias update-jupyter-notebook='cd {{ playbooksDir }}/JupyterNotebook; git pull'"
    regexp: "^alias update-jupyter-notebook="

- name: "Jupyter Notebook | set service configuration"
  ansible.builtin.template:
    src  : "../files/jupyter-notebook/jupyter-notebook.service"
    dest : "/etc/systemd/system/jupyter-notebook.service"
    mode: 0640

- name: "Jupyter Notebook | Enable service"
  ansible.builtin.systemd:
    name: jupyter-notebook
    state: started
    enabled: true
