# Sphinx Documentation setup
# Source : https://sphinx-inline-tabs.readthedocs.io/en/latest/

- name: "Sphinx documentation | remove old wiki"
  ansible.builtin.shell: rm -rf {{ documentationDir }}/wiki 

- name: "Sphinx documentation | nginx installation"
  apt:
    name: 
      - nginx 

- name: "Sphinx documentation | create wiki directory"
  become_user: "{{ ansible_user }}"
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0775
  loop:
    - "{{ documentationDir }}/wiki"

- name: "Sphinx documentation | create sphinx virtualenv"
  become_user: "{{ ansible_user }}"
  ansible.builtin.shell: cd {{ documentationDir }}/wiki; python3 -m venv __env__; 

- name: "Sphinx documentation | setup sphinx and extensions"
  become_user: "{{ ansible_user }}"
  ansible.builtin.pip:
    name: 
      - sphinx
      - myst-parser
      - sphinx-inline-tabs
    virtualenv: "{{ documentationDir }}/wiki/__env__"

- name: "Sphinx documentation | setup sphinx-themes"
  become_user: "{{ ansible_user }}"
  ansible.builtin.pip:
    name: 
      - furo
      - sphinx-rtd-theme
      - sphinx-book-theme
    virtualenv: "{{ documentationDir }}/wiki/__env__"

- name: "Sphinx documentation | create sphinx project"
  become_user: "{{ ansible_user }}"
  ansible.builtin.shell: cd {{ documentationDir }}/wiki && . __env__/bin/activate && sphinx-quickstart -q --sep -p "wiki" -a "kidrek" -v 0.1 --ext-autodoc;

- name: "Sphinx documentation | set the new theme"
  become_user: "{{ ansible_user }}"
  lineinfile:
    dest: "{{ documentationDir }}/wiki/source/conf.py"
    create: yes
    mode: 0644
    line: "html_theme = 'sphinx_book_theme'"
    regexp: "^html_theme ="

- name: "Sphinx documentation | add extensions in configuration file"
  become_user: "{{ ansible_user }}"
  lineinfile:
    path: "{{ documentationDir }}/wiki/source/conf.py"
    regexp: '^    "{{ item.name }}",'
    insertafter: '^extensions = \['
    line: '    "{{ item.name }}",'
  with_items:
    - { name: "myst_parser" }
    - { name: "sphinx_inline_tabs" }

- name: "Sphinx documentation | Download Secubian-Wiki"
  become_user: "{{ ansible_user }}"
  git:
    repo: "{{ item.repo }}"
    accept_hostkey: yes
    dest: "{{ item.dest }}"
    recursive: yes
  with_items:
    - { repo: "https://github.com/kidrek/secubian-wiki.git", dest: "/tmp/wiki" }

- name: "Sphinx documentation | remove old wiki source"
  become_user: "{{ ansible_user }}"
  ansible.builtin.shell: mv /tmp/wiki/* {{ documentationDir }}/wiki/source/; mv /tmp/wiki/.* {{ documentationDir }}/wiki/source/
  ignore_errors: true

- name: "Sphinx documentation | remove temp wiki"
  ansible.builtin.shell: rm -rf /tmp/wiki

- name: "Sphinx documentation | generate html wiki"
  become_user: "{{ ansible_user }}"
  shell: "cd {{ documentationDir }}/wiki && . __env__/bin/activate && make html"

- name: "Sphinx documentation | copy built files in /var/www/html/"
  ansible.builtin.shell: cd {{ documentationDir }}/wiki; cp -rf ./build/html /var/www/html/wiki; chown -R www-data:www-data /var/www/html/wiki; chmod 0500 -R  /var/www/html/wiki;
  ignore_errors: true

- name: "Sphinx documentation | Add alias"
  become_user: "{{ ansible_user }}"
  lineinfile:
    dest: "~/.aliases"
    create: yes
    mode: 0644
    line: "alias update-wiki='cd {{ documentationDir }}/wiki/source; git pull; cd -; cd {{ documentationDir }}/wiki/ && . __env__/bin/activate && make html; sudo rm -rf /var/www/html/wiki; sudo cp -rf ./build/html /var/www/html/wiki; sudo chown -R www-data:www-data /var/www/html/wiki; cd -'"
    regexp: "^alias update-wiki="
