- name: "Blackbird | set PythonVersion"
  ansible.builtin.set_fact:
    python_version : "3.9.18" 

- name: "Blackbird | Clone git repos"
  become_user: "{{ ansible_user }}"
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
    accept_hostkey: yes
    force: yes
    recursive: yes
  with_items:
    - { repo: "https://github.com/p1ngul1n0/blackbird", dest: "{{ OSINT_toolsDir }}/blackbird" }

- name: "Blackbird | Install python {{ python_version }}"
  become_user: "{{ ansible_user }}"
  ansible.builtin.shell: ". $HOME/.env && $HOME/.pyenv/bin/pyenv install {{ python_version }}"
  ignore_errors: true

- name: "Blackbird | Set python version"
  become_user: "{{ ansible_user }}"
  ansible.builtin.shell: "cd {{ OSINT_toolsDir }}/blackbird; $HOME/.pyenv/bin/pyenv local {{ python_version }}"

- name: "Blackbird | Requirements tools installation"
  become_user: "{{ ansible_user }}"
  ansible.builtin.pip:
    requirements: "{{ OSINT_toolsDir }}/blackbird/requirements.txt"
    virtualenv: "$HOME/.pyenv/versions/{{ python_version }}"
    virtualenv_command: "$HOME/.pyenv/bin/pyenv virtualenv {{ python_version }}"

- name: "Blackbird | Add alias"
  become_user: "{{ ansible_user }}"
  lineinfile:
    dest: "~/.aliases"
    create: yes
    mode: 0644
    line: "alias {{ item.alias }}='{{ item.commandLine }}'"
    regexp: "^alias {{ item.alias }}="
  with_items:
    - { alias: "blackbird.py", commandLine: "cd {{ OSINT_toolsDir }}/blackbird; $HOME/.pyenv/versions/{{ python_version }}/bin/python {{ OSINT_toolsDir }}/blackbird/blackbird.py" }
