- type: filestream
  enabled: true
  id: dfir-collection
  take_over: true
  paths:
    - {{ casesDir }}/**/*.json
    - {{ casesDir }}/*.json
  close_inactive: 5m
  fields_under_root: true
  fields:
    type: secubianDFIR
    file.type: json

#  json.keys_under_root: true
#  json.overwrite_keys: true
#  json.add_error_key: true
#  json.expand_keys: true

  parsers:
  - multiline:
      type: pattern
      pattern: '^({|\[)[^\n]+(}|])$'
      negate: true
      match: before
