- name: "FLARE CAPA | Retrieve the latest version"
  uri:
    url: "https://api.github.com/repos/mandiant/capa/releases/latest"
    return_content: true
  register: latest_version

- name: "FLARE CAPA | Download the latest version"
  loop: "{{ latest_version.json.assets }}"
  when: "'-linux.zip' in item.name"
  get_url:
    url: "{{ item.browser_download_url }}"
    dest: "/tmp/capa-linux.zip"

- name: "FLARE CAPA | Extract binary from archive"
  ansible.builtin.unarchive:
    src: /tmp/capa-linux.zip
    dest: /usr/bin/

- name: "FLARE CAPA | Set executable"
  ansible.builtin.shell: chmod +x /usr/bin/capa

- name: "FLARE CAPA | Clone git CAPA rules repos"
  become_user: "{{ ansible_user }}"
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
    accept_hostkey: yes
    force: yes
    recursive: yes
  with_items:
    - { repo: "https://github.com/mandiant/capa-rules.git", dest: "{{ DFIR_toolsDir }}/analyse/rules/flare-capa-rules" }

- name: "FLARE CAPA | Clone git CAPA signatures repos"
  become_user: "{{ ansible_user }}"
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
    accept_hostkey: yes
    force: yes
    recursive: yes
  with_items:
    - { repo: "https://github.com/mandiant/capa.git", dest: "{{ DFIR_toolsDir }}/analyse/rules/flare-capa-signatures" }

- name: "FLARE CAPA | Add aliases"
  become_user: "{{ ansible_user }}"
  lineinfile:
    dest: "~/.aliases"
    create: yes
    mode: 0644
    line: 'alias capa="capa --rules {{ DFIR_toolsDir }}/analyse/rules/flare-capa-rules --signatures {{ DFIR_toolsDir }}/analyse/rules/flare-capa-signatures/sigs "'
    regexp: "^alias capa="

