
- name: "CyberChef | Get latest version of CyberChef from Github API"
  become_user: "{{ ansible_user }}"
  uri:
    url: "https://api.github.com/repos/gchq/cyberchef/releases/latest"
    return_content: yes
  register: url_content

- name: "CyberChef | Set latest version tag name in cyberchef_latest_version variable"
  become_user: "{{ ansible_user }}"
  set_fact:
    cyberchef_latest_tag_name: "{{ url_content.json.tag_name }}"

- name: "CyberChef | Install"
  become_user: "{{ ansible_user }}"
  get_url:
    url: "https://github.com/gchq/cyberchef/releases/download/{{ cyberchef_latest_tag_name }}/CyberChef_{{ cyberchef_latest_tag_name }}.zip"
    dest: "{{ DFIR_toolsDir }}/data_processing/{{ cyberchef_latest_tag_name }}.zip"
    mode: 0755

- name: "CyberChef | Create directory"
  file:
    path: "/var/www/html/cyberchef/"
    state: directory
    owner: "www-data"
    group: "www-data"
    mode: 0500

- name: "CyberChef | Extract html file"
  ansible.builtin.unarchive:
    src: "{{ DFIR_toolsDir }}/data_processing/{{ cyberchef_latest_tag_name }}.zip"
    dest: "/var/www/html/cyberchef/"
    owner: "www-data"
    group: "www-data"
    mode: 0500

- name: "CyberChef | Create symbolic link"
  file:
    src: "/var/www/html/cyberchef/CyberChef_{{ cyberchef_latest_tag_name }}.html"
    dest: "/var/www/html/cyberchef/index.html"
    state: link
    owner: "www-data"
    group: "www-data"
    mode: 0500
