- name: "DidierStevensSuite | set PythonVersion"
  ansible.builtin.set_fact:
    python_version : "3.9.18" 

- name: "DidierStevensSuite | Download repository"
  become_user: "{{ ansible_user }}"
  git:
    repo: "{{ item.repo }}"
    accept_hostkey: yes
    dest: "{{ item.dest }}"
    recursive: yes
    force: true
  with_items:
    - { repo: "https://github.com/DidierStevens/DidierStevensSuite.git", dest: "{{ DFIR_toolsDir }}/data_processing/DidierStevensSuite" }

- name: "DidierStevensSuite | set executable"
  ansible.builtin.shell: chmod +x {{ DFIR_toolsDir }}/data_processing/DidierStevensSuite/*.py

- name: "DidierStevensSuite | Add PATH"
  become_user: "{{ ansible_user }}"
  lineinfile:
    dest: "~/.env"
    create: yes
    mode: 0644
    line: "export PATH=$PATH:{{ DFIR_toolsDir }}/data_processing/DidierStevensSuite"
    regexp: "^export PATH=$PATH:{{ DFIR_toolsDir }}/data_processing/DidierStevensSuite"

- name: "DidierStevensSuite | Install required python modules"
  become_user: "{{ ansible_user }}"
  ansible.builtin.pip:
    name: 
      - pyzipper
      - pycryptodome
    virtualenv: "$HOME/.pyenv/versions/{{ python_version }}"
    virtualenv_command: "$HOME/.pyenv/bin/pyenv virtualenv {{ python_version }}"

