- name: "Loki | set PythonVersion"
  ansible.builtin.set_fact:
    python_version : "3.9.18" 

- name: "Loki | Clone git repos"
  become_user: "{{ ansible_user }}"
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
    accept_hostkey: yes
    force: yes
    recursive: yes
  with_items:
    - { repo: "https://github.com/Neo23x0/Loki.git", dest: "{{ DFIR_toolsDir }}/analyse/tools/Loki" }

- name: "Loki | Python modules requirement"
  become_user: "{{ ansible_user }}"
  ansible.builtin.pip:
    requirements: "{{ DFIR_toolsDir }}/analyse/tools/Loki/requirements.txt"
    virtualenv: "$HOME/.pyenv/versions/{{ python_version }}"
    virtualenv_command: "$HOME/.pyenv/bin/pyenv virtualenv {{ python_version }}"

- name: "Loki | Threat database update"
  become_user: "{{ ansible_user }}"
  ansible.builtin.shell: cd {{ DFIR_toolsDir }}/analyse/tools/Loki; $HOME/.pyenv/versions/{{ python_version }}/bin/python ./loki-upgrader.py;

- name: "Loki | Add aliases"
  become_user: "{{ ansible_user }}"
  lineinfile:
    dest: "~/.aliases"
    create: yes
    mode: 0644
    line: 'alias loki.py="cd {{ DFIR_toolsDir }}/analyse/tools/Loki; $HOME/.pyenv/versions/{{ python_version }}/bin/python loki.py"'
    regexp: "^alias loki.py="
