- name: "Velociraptor - Retrieve the latest version"
  uri:
    url: "https://api.github.com/repos/Velocidex/velociraptor/releases/latest"
    return_content: true
  register: latest_version

- name: Prints velociraptor version
  ansible.builtin.debug:
    msg:
    - "La dernière version de Velociraptor est : {{ latest_version.json.tag_name }}"

- name: "Velociraptor - Download the latest version"
  loop: "{{ latest_version.json.assets }}"
  when: "'linux-{{ arch }}' in item.name"
  get_url:
    url: "{{ item.browser_download_url }}"
    dest: "/usr/bin/velociraptor"

- name: "Velociraptor - Set executable"
  ansible.builtin.shell: chmod +x /usr/bin/velociraptor

## Generate config
- name: "Velociraptor - Generate config"
  ansible.builtin.shell: cd /opt/; velociraptor config generate --no-interactive | tee server.config.yaml

## Create service
- name: "Velociraptor - Create service"
  ansible.builtin.shell: cd /opt/; velociraptor --config server.config.yaml debian server; dpkg -i velociraptor_server_*.deb
  ignore_errors: True

## Create user
- include_tasks: tasks/keepassXC_generate_password.yml

- name: "Velociraptor | Add Entry in keepassXC"
  become_user: "{{ ansible_user }}"
  shell: "printf \"%s\n%s\" {{ keepass_db_password }} {{ password }} | keepassxc-cli add --url 'https://127.0.0.1:8889' -u 'secubian' -p {{ keepass_db_path }} velociraptor"
  delegate_to: localhost
  register: result
  ignore_errors: False

- name: "Velociraptor - Create user"
  ansible.builtin.shell: "sudo -u velociraptor velociraptor --config /etc/velociraptor/server.config.yaml  user add secubian --role=administrator {{ password }}"

