# Volatility
- name: "Volatility | set PythonVersion"
  ansible.builtin.set_fact:
    python_version : "2.7.18" 

- name: "Volatility | Install requirements"
  apt:
    name: 
      - build-essential 
      - capstone-tool 
      - clamav
      - git-core
      - libcapstone-dev
      - libraw1394-11 
      - libssl-dev
      - tzdata
      - yara 
    state: present

- name: "Volatility | Install python libraries needed by volatility"
  become_user: "{{ ansible_user }}"
  ansible.builtin.pip:
    name: 
      - construct
      - distorm3
      - future
      - openpyxl
      - pdbparse
      - pefile
      - pillow
      - pycrypto
      - pycryptodome
      - pytz
      - setuptools
      - ujson
    virtualenv: "$HOME/.pyenv/versions/{{ python_version }}"
    virtualenv_command: $HOME/.pyenv/bin/pyenv virtualenv {{ python_version }}

- name: "Volatility | Clone git repos"
  become_user: "{{ ansible_user }}"
  git:
    repo: "{{ item.repo }}"
    accept_hostkey: yes
    dest: "{{ item.dest }}"
    force: yes
  with_items:
    - { repo: "https://github.com/volatilityfoundation/volatility.git", dest: "{{ DFIR_toolsDir }}/data_processing/volatility" }

- name: "Volatility | Set python version"
  become_user: "{{ ansible_user }}"
  ansible.builtin.shell: "cd {{ DFIR_toolsDir }}/data_processing/volatility; $HOME/.pyenv/bin/pyenv local {{ python_version }}"

#- name: "Volatility | Create YARA Symbolic Link for library"
#  ansible.builtin.file:
#    dest: "/usr/lib/libyara.so"
#    src: "/usr/local/lib/python2.7/dist-packages/usr/lib/libyara.so"
#    state: link


# Volatility Plugins 
## most of https://github.com/sans-dfir/sift-files/tree/master/volatility should be here
## src : https://github.com/juju4/ansible-volatility/blob/master/tasks/volatility-modules.yml

- name: "Volatility | Ensure volatility plugins directory exists"
  become_user: "{{ ansible_user }}"
  ansible.builtin.file:
    dest: "{{ DFIR_toolsDir }}/data_processing/volatility/volatilityplugins"
    mode: '0755'
    state: directory

- name: "Volatility | Set up plugins developed and maintained by the community"
  become_user: "{{ ansible_user }}"
  ansible.builtin.git:
    repo: https://github.com/volatilityfoundation/community.git
    dest: "{{ DFIR_toolsDir }}/data_processing/volatility/volatilityplugins/community"
    force: yes

## http://blog.jpcert.or.jp/2016/12/a-new-tool-to-d-d6bc.html
## https://blog.jpcert.or.jp/2018/08/volatility-plugin-for-detecting-cobalt-strike-beacon.html
- name: "Volatility | Artifact Analysis tool from JP-CERT"
  become_user: "{{ ansible_user }}"
  ansible.builtin.git:
    repo: https://github.com/JPCERTCC/aa-tools.git
    dest: "{{ DFIR_toolsDir }}/data_processing/volatility/aa-tools"
    force: yes

- name: "Volatility | module Autoruns"
  become_user: "{{ ansible_user }}"
  ansible.builtin.git:
    repo: https://github.com/tomchop/volatility-autoruns
    dest: "{{ DFIR_toolsDir }}/data_processing/volatility/volatilityplugins/volatility-autoruns"
    force: yes

- name: "Volatility | module Bitlocker keys retrieving"
  become_user: "{{ ansible_user }}"
  ansible.builtin.git:
    repo: https://github.com/elceef/bitlocker
    dest: "{{ DFIR_toolsDir }}/data_processing/volatility/volatilityplugins/elceef-bitlocker"
    force: yes

- name: "Volatility | module Malware config extractor - plugx, andromeda"
  become_user: "{{ ansible_user }}"
  ansible.builtin.git:
    repo: https://github.com/arbor-jjones/volatility_plugins.git
    dest: "{{ DFIR_toolsDir }}/data_processing/volatility/plugx+andromeda"
    force: yes

- name: "Volatility | Add aliases"
  become_user: "{{ ansible_user }}"
  lineinfile:
    dest: "~/.aliases"
    create: yes
    mode: 0644
    line: "alias {{ item.alias }}='{{ item.commandLine }}'"
    regexp: "^alias {{ item.alias }}="
  with_items:
    - { alias: "vol.py", commandLine: "$HOME/.pyenv/versions/{{ python_version }}/bin/python {{ DFIR_toolsDir }}/data_processing/volatility/vol.py" }


#- name: "Volatility | Create desktop file"
#  copy:
#    dest: /usr/share/applications/secubian_volatility.desktop
#    content: |
#[Desktop Entry]
#Type=Application
#Version=1.0
#Name=volatility
#Name[vi]=volatility
#GenericName=FORENSIC VOLATILITY
#Icon=terminal
#Exec=terminator -e "echo \"Command: python vol.py -h \n-----\"; cd /home/secubian/Documents/Tools/DFIR/data_processing/volatility/; $HOME/.pyenv/versions/{{ python_version }}/bin/python vol.py -h;${SHELL:-bash};"
#Terminal=true
#Categories=SECUBIAN_forensic_memory;
#Encoding=UTF-8
