
- name: "Volatility3 | Setup"
  become_user: "{{ ansible_user }}"
  ansible.builtin.pip:
    name: 
      - volatility3
      - capstone
    virtualenv: "$HOME/.pyenv/versions/3.9.18"
    virtualenv_command: "$HOME/.pyenv/bin/pyenv virtualenv 3.9.18"

- name: "Volatility3 - Windows Symbol Tables | Download repository"
  become_user: "{{ ansible_user }}"
  git:
    repo: "{{ item.repo }}"
    accept_hostkey: yes
    dest: "{{ item.dest }}"
    recursive: yes
    force: yes
  with_items:
    - { repo: "https://github.com/JPCERTCC/Windows-Symbol-Tables", dest: "{{ DFIR_toolsDir }}/volatility3-Windows_symbol_tables" }

- name: "Volatility3 - Windows Symbol Tables | Copy to volatility3 directory"
  become_user: "{{ ansible_user }}"
  ansible.builtin.shell: mv {{ DFIR_toolsDir }}/volatility3-Windows_symbol_tables/symbols/windows/* $HOME/.pyenv/versions/3.9.18/lib/python3.9/site-packages/volatility3/symbols/windows/; rm -rf {{ DFIR_toolsDir }}/volatility3-Windows_symbol_tables;

- name: "Volatility3 | Download and unarchive Windows Symbol Tables to volatility3 directory"
  become_user: "{{ ansible_user }}"
  ansible.builtin.unarchive:
    src: "{{ item.src }}"
    dest: $HOME/.pyenv/versions/3.9.18/lib/python3.9/site-packages/volatility3/symbols/
    remote_src: yes
  with_items:
    - { src: "https://downloads.volatilityfoundation.org/volatility3/symbols/windows.zip"}
    - { src: "https://downloads.volatilityfoundation.org/volatility3/symbols/linux.zip"}
    - { src: "https://downloads.volatilityfoundation.org/volatility3/symbols/mac.zip"}


- name: "Volatility3 | Add aliases"
  become_user: "{{ ansible_user }}"
  lineinfile:
    dest: "~/.aliases"
    create: yes
    mode: 0644
    line: "alias {{ item.alias }}='{{ item.commandLine }}'"
    regexp: "^alias {{ item.alias }}="
  with_items:
    - { alias: "volatility3", commandLine: "vol " }


#- name: "Volatility3 | Download memory sample"
#  become_user: "{{ ansible_user }}"
#  get_url:                                                           
#    url: "https://s3-eu-west-1.amazonaws.com/course.oc-static.com/courses/1750151/OC-002-memdump.zip"                       
#    dest: "{{ casesDir }}"
  
